### ISSUE TITLE
Not picking up content of project in initial commit 

### ISSUE THREAD

**Issue by BenStuart** [github-for-unity/Unity#971] opened 2018-11-29 06:04 UTC
So I have an existing project i'd like to now version control.

How would I got about doing that?

typically github plugins for IDE's I've used in the past will have all files in the project as part of the initial commit.

This just had a .gitignore file and an empty asset folder.

**Comment by markjhunsinger** [comment] 2018-12-07 02:58
I just had this issue as well. What worked for me was closing Unity and opening it back up. After a refresh, all of the project were listed under Changes. Hope it helps.

**Comment by BenStuart** [comment] 2018-12-08 02:49
Hmm. Yea I gave that a go. I ended up using github desktop, picked everything up for the first commit for me. not as nice as it's not integrated into the IDE but works well.

**Comment by StanleyGoldman** [comment] 2018-12-10 14:30
Hey @BenStuart sorry for taking so long to get back to you. I'm spinning a few different plates at the same time and you are on my queue.

My immediate question is do things work correctly with a brand new Unity project. We have an existing bug #871 (that is quite hard to solve) and I wonder if that is what is affecting you currently.

**Comment by StanleyGoldman** [comment] 2019-02-14 12:33
I'm going to close this issue and assume that #871 is the root cause.
If you feel differently, please feel free to re-open this issue.

**Closed by StanleyGoldman** 2019-02-14 12:33 UTC
Labels: bug, more-information-needed
