### ISSUE TITLE
Imported files aren't automatically added to git changes list

### ISSUE THREAD

**Issue by BrentCarter** [github-for-unity/Unity#906] opened 2018-09-05 19:34 UTC
### Prerequisites

Log seems to have nothing of interest, just this:
180905-15:23:36.133  INFO [ 1] <Global>                            Initializing GitHubForUnity:'v1.0.2' Unity:'v2018.2.6f1'
180905-15:24:02.339  INFO [ 1] <Global>                            Initializing GitHubForUnity:'v1.0.2' Unity:'v2018.2.6f1'

### Description

I imported an asset from the Asset store (Dissonance Chat) and those files weren't added to git, even though many of them are under the Assets folder which is being added to git.

### Steps to Reproduce

1. Import a new asset from the asset store.
2. Go to GitHub for Unity panel and view the Changes tab.

**Expected behavior:** [What you expect to happen]

I expected to see all the newly added files in the change list.

**Actual behavior:** [What actually happens]

No files are added

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Additional Information

Am I missing something here?  I'm used to changes and additions showing up in version control "change" lists...  does git and/or this plugin work differently?

**Comment by BrentCarter** [comment] 2018-09-05 19:44
I just installed GitHub desktop to get another view into what might be happening.  Upon install (and LFS initialization), it immediately shows 557 changed files.  I closed and re-opened Unity and still the Github for Unity plugin changed file list shows nothing.  I guess I'll commit using GitHub Desktop and then keep an eye on whether Github for Unity sees other new files as they are added.

**Comment by BrentCarter** [comment] 2018-09-05 20:58
Once I checked in via GitHub Desktop, Github for Unity could then pick up changes to those files and show them properly in the changes tab.  Is this a bug or am I misunderstanding something?

**Comment by BrentCarter** [comment] 2018-09-05 21:01
Interestingly, I just imported via "Right click on Assets > Import Package > Custom Package..." and Github for Unity immediately picked up the new files.  Perhaps the issue is just when importing directly after downloading in the Asset Store?

**Comment by StanleyGoldman** [comment] 2018-09-12 20:38
Hey @BrentCarter thanks for trying our stuff out and filing this issue.
Sorry I haven't gotten to reply sooner, I've been working on a few of my other projects.

I'm gonna dig into this a bit later and let you know what I think. It sounds similar to #907 for some reason.

**Comment by StanleyGoldman** [comment] 2018-10-03 19:29
@BrentCarter 

Sorry it's taken so long, this problem is obscure. I believe you are all "stuck" in a state where your cache has invalidated, it tried once to validate it, and it no longer attempts to validate. So your logs show up empty.

I think I have gotten closer to solve the issue, but I need your help in testing this next build.

https://ci.appveyor.com/api/buildjobs/ehbdp9cf383c4lj7/artifacts/github-for-unity-1.1.0.6098.unitypackage

This may not fix your error, but it will allow the "Refresh" button to "try again". And hopefully between that and the new logs we capture, we can solve all of your problems.

Please give it a shot and let me know how it goes.

**Comment by StanleyGoldman** [comment] 2018-10-04 18:38
My build server screwed me and that previous link won't install correctly. Unzip and try this instead.

[github-for-unity-1.1.0.4985-715e1de7.unitypackage.zip](https://github.com/github-for-unity/Unity/files/2447668/github-for-unity-1.1.0.4985-715e1de7.unitypackage.zip)

**Comment by BrentCarter** [comment] 2018-10-05 15:20
I created a new Unity project, imported the zip above, did "create new repo" from your plugin, imported the Dissonance plugin and no files showed up in your "changes" tab.  I expected to see the new Dissonance files.  I clicked the "Refresh" button and still see nothing. I went to GitHub Desktop and see all the Dissonance files.  So, unless I'm doing something wrong, it doesn't seem fixed to me.  Is this a sufficient test?

**Comment by StanleyGoldman** [comment] 2018-10-05 15:29
Hey @BrentCarter Sorry if i mis-explained, it's not going to be fixed with this build, but it will help me get more data in the logs. Can you try to repro and send me the log file?

**Comment by BrentCarter** [comment] 2018-10-05 15:45
Is this the one you want?

C:\Users\username\AppData\Local\Unity\Editor.log

Does the unity log really not put timestamps in?!?  That file is huge so was going to pick off just the test but hard to tell exactly where it starts...  I think I have it but it is still about 1000 lines - is there another way to send to you other than dumping in here?  Or is that what you want?

**Comment by BrentCarter** [comment] 2018-10-05 15:46
Oh, and I thought you'd meant it wasn't fixed "automatically" but the refresh might work.  Anyway, no worries...

**Comment by StanleyGoldman** [comment] 2018-10-05 15:59
You should find the file I'm looking for here... `AppData\Local\GitHubUnity\github-unity.log`
You can drag the file right here to attach it.

**Comment by BrentCarter** [comment] 2018-10-05 16:02
Not much there...  but here it is:

[github-unity.log](https://github.com/github-for-unity/Unity/files/2451070/github-unity.log)

**Comment by StanleyGoldman** [comment] 2018-10-05 16:38
Can you go an enable Trace debugging? It's on the Settings tab.
Then we should have a bit more details about what is happening...

**Comment by BrentCarter** [comment] 2018-10-05 18:06
Perhaps a timeout?

[github-unity.log](https://github.com/github-for-unity/Unity/files/2451646/github-unity.log)

**Comment by StanleyGoldman** [comment] 2018-10-05 19:05
Hmm. Are you on discord? Would you be able to do a video call?

**Comment by StanleyGoldman** [comment] 2018-10-05 19:17
Discord: https://discord.gg/dnxD4CV

**Comment by BrentCarter** [comment] 2018-10-05 19:18
Never used it...  Skype?

**Comment by BrentCarter** [comment] 2018-10-05 21:46
I sent you a Skype invite earlier...  did you get it?

**Comment by BrentCarter** [comment] 2018-10-07 15:46
Is there a way to get it to you outside this public thread?

**Comment by StanleyGoldman** [comment] 2018-10-08 11:06
sure.. `[MyUsername]@github.com`

**Comment by StanleyGoldman** [comment] 2018-10-08 16:47
I'm finally able to reproduce this, it is a duplicate of #871

**Closed** 2018-10-08 16:48 UTC
Labels: bug, duplicate

**Comment by BrentCarter** [comment] 2018-10-08 16:59
Ok, so you don't need anything from me at this point then, right?

**Comment by StanleyGoldman** [comment] 2018-10-08 17:19
Nope, I'm all good. thanks for hanging in there.
