### ISSUE TITLE
Unzipped resources cannot be directly moved between drives

### ISSUE THREAD

**Issue by MonsieurGallo** [github-for-unity/Unity#898] opened 2018-08-27 21:54 UTC
### Description

I can't get the editor extension to work. I downloaded it, and open the github tab, and the loading icon just kept spinning. I went to settings, and **git installation** -> **path to git** and **path to git lfs** where empty. I tried setting it with the **find system git button** and it displayed the path, but when I clicked **save** and changed to another tab, it was still loading with. In the settings tab, the option to set the path was frozen for some time. I tried using the **set to bundled git button**, but it didn't work. It showed an error saying _'error validating git path'_. I also tried setting the path manually but didn't suceed. 

### Steps to Reproduce

1. Install Github for unity from the asset store. (I had a previous installation of git and github, I don't know if that may have caused the problem)
2. Open the github tab in the editor. 

I attach the log and a log that was marked as old.

[github-unity.log](https://github.com/github-for-unity/Unity/files/2325763/github-unity.log)
[github-unity-old.log](https://github.com/github-for-unity/Unity/files/2325764/github-unity-old.log)

**Comment by StanleyGoldman** [comment] 2018-08-28 21:08
Hey @MonsieurGallo thanks for testing our stuff out.

This issue sounds like other issues I am trying to sniff out. I will come back to you on this.

**Comment by StanleyGoldman** [comment] 2018-10-04 18:33
Hmm, it seems my build server is not making packages accurately yet. Please unzip and try this instead.

[github-for-unity-1.1.0.4986-ae4f4f65.unitypackage.zip](https://github.com/github-for-unity/Unity/files/2447626/github-for-unity-1.1.0.4986-ae4f4f65.unitypackage.zip)

**Comment by StanleyGoldman** [comment] 2018-10-05 12:39
Word on the street is that build fixes the issue. Give it a shot and let me know.

**Comment by IgnisIncendio** [comment] 2018-10-08 06:47
I believe this is from build 1.1.0.4987:

[github-unity-old.log](https://github.com/github-for-unity/Unity/files/2454877/github-unity-old.log)
[github-unity.log](https://github.com/github-for-unity/Unity/files/2454878/github-unity.log)

**Comment by StanleyGoldman** [comment] 2018-10-08 16:50
This is a duplicate of #836

**Closed** 2018-10-08 16:50 UTC
Labels: bug, duplicate

**Comment by StanleyGoldman** [comment] 2018-10-09 10:43
@MonsieurGallo which build version did you test? Also, I need the log file to know what went wrong...
Could you try to get the log file or try to repro the issue again?
