### ISSUE TITLE
Support for other Git based source control sites (GitLab, BitBucket, etc.)

### ISSUE THREAD

**Issue by HeadClot** [github-for-unity/Unity#204] opened 2017-08-19 04:02 UTC
Hey the following is a feature request for Git for Unity.

Would it be possible to support other source control sites such as Gitlab or Bitbucket with Git for Unity?

**Comment by sandeepkumarp** [comment] 2017-08-19 05:35
That would be great. My up-vote for this feature request,

**Comment by StanleyGoldman** [comment] 2017-08-19 22:50
Hey @HeadClot and @sandeepkumarp. Thanks for checking out our plugin.

Question, did you try to use another host yet with it? I haven't tried it yet, but it should just work 😉.

Git is git after all and this is just a git client.

**Comment by HeadClot** [comment] 2017-08-22 00:55
So - Github for unity gives a dialog that says 

Username:
Password:

I am assuming that this is for github authentication. It has no way to enter which site (Bitbucket, Gitlab, etc.) to use. I feel that this could use some improvement.

**Comment by StanleyGoldman** [comment] 2017-08-22 10:38
Obviously you wont be able to authenticate to other providers with this tool. That's just for authenticating to GitHub. :trollface: Everything else should just work...

Existing Project
1. Make sure you can perform git operations on the command line to your chosen provider.
2. Clone it on the command l ine
3. Open it Unity & install GitHub for Unity
4. Fetch/Push/Pull should just work

New Project
1. Make sure you can perform git operations on the command line to your chosen provider.
2. Open a new Unity Project and install GitHub for Unity.
3. Create your repo with your provider, Save the git url in Settings in GitHub for Unity
4. Fetch/Push/Pull should just work

**Comment by HeadClot** [comment] 2017-08-27 11:40
Hey @StanleyGoldman Thank you for the clarification :)

**Comment by chall3ng3r** [comment] 2017-09-02 18:30
Great!

I always use GitHub Desktop or SourceTree to init my repos, afterwards I just manage them from within the app (VSCode, VS, etc.).

Thanks for bringing Git support into Unity, it'll be a lot easy with this plugin.

**Comment by asztalosdani** [comment] 2017-11-05 09:32
I just got it working with a Bitbucket repo.
I think it would make sense to rename this tool to something like "Git for Unity", because as I see it now, the only GitHub specific thing is the sign in window.

**Comment by StanleyGoldman** [comment] 2017-11-06 13:42
Sounds like people are able to connect to other providers. So I'm going to close this issue for now.

**Closed by StanleyGoldman** 2017-11-06 13:42 UTC
Labels: question

**Comment by StanleyGoldman** [comment] 2017-11-06 15:54
BTW @asztalosdani 

Of course we plan to have more features than just login. We only just got started.
The problem is that Unity does not have a basic git client so we had to start there.

_(also we work for GitHub)_ 😄

**Comment by Imafikus** [comment] 2019-08-16 20:25
Any update on this maybe?
