### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by nickmccurdy** [github-for-unity/Unity#408] opened 2017-11-05 21:26 UTC
### Description

When adding GitHub for Unity to an existing Unity project with or without an existing git repository, the plugin crashes with the following error and the plugin's window in Unity is blank.

### Steps to Reproduce

1. Open a Unity project without the plugin, with or without a git repository in the same directory.
2. Install the Unity plugin into the project.
3. View the error log and the blank plugin window.

**Expected behavior:** [What you expect to happen]
- No errors
- Plugin Displays

**Actual behavior:** [What actually happens]
- Errors
- Plugin window is blank

```
NullReferenceException: Object reference not set to an instance of an object
GitHub.Unity.StreamExtensions.<StreamExtensions>m__3 (UnityEngine.Texture2D tex, System.IO.MemoryStream ms) (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Utility.cs:173)
GitHub.Unity.StreamExtensions.ToTexture2D (System.IO.Stream input) (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Utility.cs:191)
GitHub.Unity.Utility.GetIcon (System.String filename, System.String filename2x) (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Utility.cs:78)
GitHub.Unity.Styles.GetFileStatusIcon (GitFileStatus status, Boolean isLocked) (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Styles.cs:127)
GitHub.Unity.ProjectWindowInterface.OnProjectWindowItemGUI (System.String guid, Rect itemRect) (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ProjectWindowInterface.cs:251)
UnityEditor.ObjectListArea+LocalGroup.DrawItem (Rect position, UnityEditor.FilterResult filterItem, UnityEditor.BuiltinResource builtinResource, Boolean isFolderBrowsing) (at /Users/builduser/buildslave/unity/build/Editor/Mono/ObjectListLocalGroup.cs:856)
UnityEditor.ObjectListArea+LocalGroup.DrawInternal (Int32 beginIndex, Int32 endIndex, Single yOffset) (at /Users/builduser/buildslave/unity/build/Editor/Mono/ObjectListLocalGroup.cs:203)
UnityEditor.ObjectListArea+Group.Draw (Single yOffset, Vector2 scrollPos, System.Int32& rowsInUse) (at /Users/builduser/buildslave/unity/build/Editor/Mono/ObjectListGroup.cs:154)
UnityEditor.ObjectListArea.HandleListArea () (at /Users/builduser/buildslave/unity/build/Editor/Mono/ObjectListArea.cs:1364)
UnityEditor.ObjectListArea.OnGUI (Rect position, Int32 keyboardControlID) (at /Users/builduser/buildslave/unity/build/Editor/Mono/ObjectListArea.cs:564)
UnityEditor.ProjectBrowser.OnGUI () (at /Users/builduser/buildslave/unity/build/Editor/Mono/ProjectBrowser.cs:1780)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:285)
UnityEditor.HostView.Invoke (System.String methodName) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:278)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:245)
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

#### Versions
- Unity 2017.2.0f3 Personal
- `github-for-unity-0.21.1.2540-b3634838`

#### Screenshot
![image](https://user-images.githubusercontent.com/927220/32419293-ad0e4806-c245-11e7-855d-d7ce1d869f7c.png)

**Comment by StanleyGoldman** [comment] 2017-11-05 21:40
Hey @nickmccurdy. Thanks for testing our stuff.
This is a duplicate of #351. It only affects 2017.2 and will be fixed in the next release.

**Closed by StanleyGoldman** 2017-11-05 21:40 UTC
Labels: bug, duplicate, unity2017.2

**Comment by nickmccurdy** [comment] 2017-11-05 22:09
Thanks, since that's closed does that mean this issue is fixed and I should just wait for the next release or build off master?

**Comment by StanleyGoldman** [comment] 2017-11-05 22:16
Yea, we should be pushing out the next release this week I hope.
