### ISSUE TITLE
MacOS Unity Editor Freeze when "Stop"

### ISSUE THREAD

**Issue by guitarrapc** [github-for-unity/Unity#147] opened 2017-07-28 05:01 UTC
### Prerequisites

- On macOS, the extension log file is at `~/.local/share/GitHubUnity/github-unity.log`

No log exists

### Description

MacOS Unity Editor will be hung and throw Exception when Stopping Editor play.

Error message are as follows.

> Fatal Error!
> ChackDisallowAllocation. Allocating memory when it is not allowed to allocate memory.

### Steps to Reproduce

1. Create New Project
2. Import Github  For Unity v1.5.0 from Release Tab : https://github.com/github-for-unity/Unity/releases/tag/v0.15-alpha
3. "Play" on the Unity Editor
4. Stop.

You will see Exception popup.

**Expected behavior:** [What you expect to happen]

No Exceptions!

**Actual behavior:** [What actually happens]

Exception happen and Unity Editor will hung. Sometimes crush with mac itself.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Everytime.

### Additional Information

- Unity 5.6.2p3 - 5.6.2p4
- macOS Sierra ver:10.12.3

**Comment by shana** [comment] 2017-07-28 09:47
@guitarrapc Could you post your Unity Editor log file here please?

**Comment by guitarrapc** [comment] 2017-07-29 03:31
OK, I'll check it. Give me a time.

**Comment by guitarrapc** [comment] 2017-07-30 16:50
I reproduce on my macOS and got Editor.log

# Error Screenshot

<img width="1680" alt="screenshot" src="https://user-images.githubusercontent.com/3856350/28755255-8b405a58-7591-11e7-9b0d-90435017ad50.png">

# ErrorLog

https://gist.github.com/guitarrapc/dba04dcdea98b74a2b5c7346de827405

**Comment by StanleyGoldman** [comment] 2017-08-09 12:38
Hey @guitarrapc. Would you mind downloading the latest build and letting us know how that works out for you?

**Comment by guitarrapc** [comment] 2017-08-09 14:39
Sure. I'll check it.

**Comment by guitarrapc** [comment] 2017-08-14 02:40
@StanleyGoldman I've checked with 0.16.0-alpha but unfortunately it repeated again 😢 
Here's Editor.log when Unity crushed.

> https://gist.github.com/guitarrapc/dba04dcdea98b74a2b5c7346de827405#file-githubforunity-crash-unityeditor-0-16-0-alpha-log

**Comment by guitarrapc** [comment] 2017-08-14 03:30
Issue happens on several machines. Is anyone reproduce this issue?

**Comment by StanleyGoldman** [comment] 2017-08-14 12:20
Hey @guitarrapc, thanks for testing again. Sorry this is happening. I'm trying to work on this today.
Would you mind stopping by the gitter chat pinging me?

**Comment by StanleyGoldman** [comment] 2017-08-14 15:54
Okay, so some updates.

1. I am not able to reproduce this on my mac.
2. This issue is a duplicate of #60 
3. This is the relevant google for the error: https://www.google.com/search?q=mono_unity_liveness_calculation_from_statics
4. We are working on it...

**Comment by StanleyGoldman** [comment] 2017-08-14 15:54
Okay, so some updates.

1. I am not able to reproduce this on my mac.
2. This issue is a duplicate of #60 
3. This is the relevant google for the error: https://www.google.com/search?q=mono_unity_liveness_calculation_from_statics
4. We are working on it...

**Comment by StanleyGoldman** [comment] 2017-08-14 15:55
I'm going to close this one out now, if you have any more updates please refer to issue #60

**Closed by StanleyGoldman** 2017-08-14 15:55 UTC
Labels: bug, duplicate, macos
