### ISSUE TITLE
Couldn't Push

### ISSUE THREAD

**Issue by unityHUI** [github-for-unity/Unity#146] opened 2017-07-27 10:02 UTC
I config a project and i setup everything when i push appears that can't push!
the log show “could not read Username for 'https://github.com': Invalid argument” ，but the link is Right
I don‘t know where the error occurred 
here is  the Log

[github-unity.zip](https://github.com/github-for-unity/Unity/files/1179538/github-unity.zip)

**Comment by shana** [comment] 2017-07-28 09:49
Hi @unityHUI 

What version of Unity are you running and which OS is it? Could you also send your Unity Editor log please, so we can figure out what's going on?

Thanks!

**Comment by unityHUI** [comment] 2017-08-09 01:21
Oh， I'm so sorry to respond  you so late,My Unity verison is 5.5.0，OS is Window 7 64bit，here is the Unity Editor Log
[Editor.zip](https://github.com/github-for-unity/Unity/files/1210019/Editor.zip)
Thanks！

**Comment by StanleyGoldman** [comment] 2017-09-12 16:01
Hey @unityHUI 

Have you tested against the latest version of our plugin?

**Comment by StanleyGoldman** [comment] 2017-09-16 00:03
I believe this is a duplicate of #278 so it should be fixed soon

**Closed by StanleyGoldman** 2017-09-16 00:03 UTC
Labels: more-information-needed
