### ISSUE TITLE
After a certain number of changes, no changes are displayed locally

### ISSUE THREAD

**Issue by shafy** [github-for-unity/Unity#899] opened 2018-08-27 22:24 UTC
### Description

After adding a couple of hundred files (importing assets), the changes just stop showing up completely (also the previously shown changed files are now gone from the "Changes" tab). 

This is logged if I add a new empty script:

```
180827-15:20:48.937 TRACE [ 1] <GitLocksCache>                     needsInvalidation isInitialized:True timedOut:True
180827-15:20:48.938 TRACE [181] <ProcessWrapper>                    Running '/usr/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
180827-15:20:48.948 TRACE [182] <ProcessWrapper>                    Running '/usr/local/bin/git-lfs locks --json'
```

### Steps to Reproduce

1. Open a new project
2. Install GitHub plugin
3. Publish repo
4. Import hundreds of asset files
5. "Changes" tab starts showing changed files
6. Import more files
7. "Changes" tab suddenly stops showing any changes at all (also older changed files are gone)

**Expected behavior:** Show all changed files.

**Actual behavior:** Shows 0 changed files.

**Reproduces how often:** 100%

**Comment by StanleyGoldman** [comment] 2018-08-28 20:56
Hey @shafy Thanks for testing our stuff out.

You don't happen to have a public repo I could clone to try to reproduce this error would you?
I tried a while back stress testing this thing with changes. I got pretty high without showing trouble...

Would you happen to have a closer count on how many? Also what types of files?
Maybe you can look at your commit history and let me know..

**Comment by shafy** [comment] 2018-08-28 21:10
Here, I made the repo public. It's non-sense test anyways :-) https://github.com/shafy/unity-kosmos-test-6

If you clone this project and add the GitHub plugin in Unity, adding more files doesn't show the changed files.

Regarding your questions:
- It was a whole folder, so I don't know which file type
- Ended up not committing and created a new repo through git command line

**Comment by StanleyGoldman** [comment] 2018-09-17 20:07
So I'm testing your project with Unity 2018.2 and GitHub for Unity 1.0.3.
I'm  able to make changes, but so far I'm unable to view the history of your project. I'm still looking into it.

**Comment by shafy** [comment] 2018-09-18 18:43
Cool. I used GitHub for Unity 1.0.2, Unity 2018.2.6f1 (right now I'm using this, not sure if I upgraded in the meantime to be honest) and macOS High Sierra 10.13.6

**Comment by StanleyGoldman** [comment] 2018-10-03 14:52
Okay, so there is a caching issue that I'm looking to debug, but your repo pointed me to a different issue.

https://github.com/shafy/unity-kosmos-test-6/commit/9d11c855260edbc19f9c51ab374c2f795d318b0c

This commit right here deletes a file named `c:UsersOculusGoVideo.mp4` which completely throws off my ability to read your log.

**Comment by StanleyGoldman** [comment] 2018-10-03 15:35
Okay, that's solved, now to figure out this caching issue for good.

**Comment by StanleyGoldman** [comment] 2018-10-03 18:37
hey @shafy 

I believe you are all "stuck" in a state where your cache has invalidated, it tried once to validate it, and it no longer attempts to validate. So your logs show up empty.

I think I have gotten closer to solve the issue, but I need your help in testing this next build.

https://ci.appveyor.com/api/buildjobs/ehbdp9cf383c4lj7/artifacts/github-for-unity-1.1.0.6098.unitypackage

This build contains the fix from #921 and #923. I think this will help us find what your next problem is.

**Comment by StanleyGoldman** [comment] 2018-10-04 18:38
My build server screwed me and that previous link won't install correctly. Unzip and try this instead.

[github-for-unity-1.1.0.4985-715e1de7.unitypackage.zip](https://github.com/github-for-unity/Unity/files/2447665/github-for-unity-1.1.0.4985-715e1de7.unitypackage.zip)

**Comment by StanleyGoldman** [comment] 2018-10-05 14:08
🐑 👋 I know we've taken a long time to figure this one out, but I'd like to get it figured out for the next release. 😅 @shafy

**Comment by shafy** [comment] 2018-10-05 17:12
hey @StanleyGoldman not sure what I'm missing but I can't install the package. How do I need to do it?

**Comment by StanleyGoldman** [comment] 2018-10-05 18:31
Unzip the file first..

**Comment by StanleyGoldman** [comment] 2018-10-05 18:31
Dunno if you noticed that

**Comment by shafy** [comment] 2018-10-05 18:38
Yeah I did. And the there are a bunch of folders and Unity doesn't let me import them as packages.

**Comment by StanleyGoldman** [comment] 2018-10-05 19:04
Are you on discord? would you like to do a video call?

**Comment by shafy** [comment] 2018-10-05 19:10
Yeah my tag is shafyy#6778

**Comment by StanleyGoldman** [comment] 2018-10-05 19:17
Sent you an invite, otherwise find me here.. https://discord.gg/dnxD4CV

**Comment by StanleyGoldman** [comment] 2018-10-08 16:46
I'm finally able to reproduce this, I'm sure this is a duplicate of #871

**Closed** 2018-10-08 16:46 UTC
Labels: bug, duplicate
