### ISSUE TITLE
Switching branch does not refresh project window

### ISSUE THREAD

**Issue by m-ronchi** [github-for-unity/Unity#900] opened 2018-08-29 15:39 UTC
### Description

Switching branch from github window does not refresh assets / project window

### Steps to Reproduce

1. create a new project, initialize repo and commit to master
2. create a new branch, e.g. feature/foo
3. create a new asset /e.g. Sprites/Square)
4. commit
5. switch back to master while Assets folder is visible

**Expected behavior:**
asset folder is refreshed and created asset disappears

**Actual behavior:**
asset remains visible in project until you refresh (i.e. switch focus to another app, then back to unity)

**Reproduces how often:** always

### Additional Information

same thing happens backwards (e.g. if you switch from master to feature/foo, you will not see square until you refresh

[github-unity.log](https://github.com/github-for-unity/Unity/files/2332781/github-unity.log)

**Comment by meaghanlewis** [comment] 2018-09-04 17:34
Related to #882

**Comment by StanleyGoldman** [comment] 2018-09-12 20:40
Sounds like #907 also

**Comment by StanleyGoldman** [comment] 2018-09-12 20:58
Yep, it's a duplicate of #882

**Comment by StanleyGoldman** [comment] 2018-09-17 19:16
I've got a fix for this coming soon.

**Closed** 2018-10-03 14:40 UTC
Labels: bug, duplicate
