### ISSUE TITLE
Add .editorconfig to ease contribution to the project

### ISSUE THREAD

**Issue by MunchyYDL** [github-for-unity/Unity#248] opened 2017-08-30 15:54 UTC
I think it would be a good idea to add a .editorconfig file with some of the projects code styles configured. As this would potentially minimise the amount of formatting errors in future PRs. :)

**Comment by StanleyGoldman** [comment] 2017-08-30 16:41
I agree, an `.editorconfig` is probably a good thing.

I always forget that `.editorconfig` is just the basic stuff like tabs/spaces and tab/space width and such. I wish there were something really cool for code formatting, but that only always just get's you 4/5's of the way there.

Feel free to take this on if you like.

**Comment by MunchyYDL** [comment] 2017-08-30 17:55
Sure, I will grab this and get an initial configuration in place. :)

**Comment by divayprakash** [comment] 2017-09-27 23:20
@MunchyYDL Working on it!

**Comment by garg000dhruv** [comment] 2017-10-04 07:20
In the spirit of _HacktoberFest_, I can pick this up. Let me know if you guys still need it.

**Comment by idealadarsh** [comment] 2017-10-08 08:22
@leereilly @StanleyGoldman I'd like to work on this issue.

**Comment by StanleyGoldman** [comment] 2017-10-09 14:28
Cool beans man.

**Comment by Frozenfire92** [comment] 2018-03-21 21:37
Was looking at #350 and it seems it is on hold and the repository deleted. Having some experience with editorconfig files I hope to help clear up some confusion and start some discussion.

From the [website](http://editorconfig.org):

> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

An analogy from many javascript projects (not sure c# equivalents)

- EditorConfig sets the text editors tab/spaces, width, etc when working on this project
- eslint, jshint, etc are tools for validating rules (with optional editor plugins), which could also test for EditorConfig rules

From what I can tell, this [projects styleguide](https://github.com/github-for-unity/Unity/blob/master/docs/contributing/styleguide.md) most of these rules would fall into the linter category, which I think is beyond the scope of EditorConfig.

It seems many of the options in #350 come from [Visual Studio 2017's integration reference](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference) and potentially this [article](http://kent-boogaart.com/blog/editorconfig-reference-for-c-developers)

However those rules may be specific to VS2017. I suspect many developers will use that as its Unity's default, but I wonder about other editors support, and if maintaining these rules is worth the effort for something that is meant to make things simple and consistent. I would assume that many editor's will support the c# solution, so [this list](https://github.com/github-for-unity/Unity/blob/master/GitHub.Unity.sln.DotSettings#L2-L32) should be improved / tested against other editors instead of using single editor specific properties.

I would propose we take a simpler approach to editorconfig like so

[EditorConfig property reference](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties)

```
# http://EditorConfig.org

root = true

[*]
indent_size = 4
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true
```

**Comment by StanleyGoldman** [comment] 2018-03-27 15:34
Hey @Frozenfire92 thanks for participating.

Yea, I think a large part of the problem in #350 was that it was a bit too much too soon. _(I just closed that pull request.)_ It seemed like the pull request was attempting to add a large template without regard to the code styles we value in this project.

The other part of the problem is there would not be a uniform way of applying the editor styles in both Visual Studio 2015 and Visual Studio 2017.

Something that you proposed that should work a bit more universally would be appreciated. If you want to put that in a pull request I can see about getting that merged in.

**Comment by Frozenfire92** [comment] 2018-04-07 20:49
After finally going to do this I noticed its already in the project

https://github.com/github-for-unity/Unity/blob/master/.editorconfig

Unless the two options I proposed above are desired this could likely be closed

```
insert_final_newline = true
trim_trailing_whitespace = true
```

**Comment by StanleyGoldman** [comment] 2018-04-09 13:38
😓... oh... sorry about that... i forgot..

Those two settings sound positive to me
Send it in a pull request and we can close this issue out.

**Closed** 2018-04-16 12:41 UTC
Labels: enhancement, good first issue, hacktoberfest, help wanted, up-for-grabs
