### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by GalHorowitz** [github-for-unity/Unity#351] opened 2017-10-09 13:51 UTC
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Application Support/GitHubUnity/github-unity.log`

### Description

Right after installing the extenstion, and opening the Github Window the console is spammed with errors and the window is blank. The settings window works tho.

### Steps to Reproduce

1. [First Step]
Install Github for Unity
2. [Second Step]
Open the Github Window
3. [and so on...]
Look at console

**Expected behavior:** [What you expect to happen]
For the window to show up with no errors
**Actual behavior:** [What actually happens]
The window is blank and there are errors
**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time
### Additional Information
I have Unity 2017.2.0b5 (64-bit) and the latest Github for Unity release.
Any additional information, configuration or data that might be necessary to reproduce the issue.
[github-unity.log](https://github.com/github-for-unity/Unity/files/1368670/github-unity.log)

**Comment by StanleyGoldman** [comment] 2017-10-09 14:33
hey @GalHorowitz thanks for testing!

So this is one of those bugs where I'm not going to get the information we need through our log file.
I need you to copy and paste the full log message from the console in Unity that gave you this message...

**Comment by GalHorowitz** [comment] 2017-10-09 14:44
I noticed another error:
```
NullReferenceException: Object reference not set to an instance of an object
GitHub.Unity.StreamExtensions.<StreamExtensions>m__3 (UnityEngine.Texture2D tex, System.IO.MemoryStream ms) (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Utility.cs:173)
GitHub.Unity.StreamExtensions.ToTexture2D (System.IO.Stream input) (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Utility.cs:191)
GitHub.Unity.Utility.GetIcon (System.String filename, System.String filename2x) (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Utility.cs:78)
GitHub.Unity.Styles.get_SmallLogo () (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Styles.cs:681)
GitHub.Unity.Window.OnEnable () (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:95)
UnityEditor.EditorWindow:GetWindow(Type[])
GitHub.Unity.Window:ShowWindow(IApplicationManager) (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:62)
GitHub.Unity.Window:GitHub_ShowWindow() (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:50)
```

**Comment by StanleyGoldman** [comment] 2017-10-09 15:20
Thanks @GalHorowitz this is what we needed.

**Comment by GalHorowitz** [comment] 2017-10-14 15:43
Is there any way to subscribe to notifications about this issue, so I would know when it's fixed?

**Comment by shiena** [comment] 2017-10-24 18:23
I think that this change is affected.
https://unity3d.com/jp/unity/whats-new/unity-2017.2.0
> Backwards Compatibility Breaking Changes
> * Scripting: UnityEngine.dll is now split into separate dlls for each UnityEngine module.

So, it seems to be solved in this way.
http://answers.unity3d.com/questions/206665/typegettypestring-does-not-work-in-unity.html

```diff
diff --git a/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Utility.cs b/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Utility.cs
index e645e565..0deb4c97 100644
--- a/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Utility.cs
+++ b/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Utility.cs
@@ -32,7 +32,7 @@ namespace GitHub.Unity

         static StreamExtensions()
         {
-            var t = typeof(Texture2D).Assembly.GetType("UnityEngine.ImageConversion", false, false);
+            var t = Assembly.Load("UnityEngine.dll").GetType("UnityEngine.ImageConversion", false, false);
             if (t != null)
             {
                 // looking for ImageConversion.LoadImage(this Texture2D tex, byte[] data)
```

**Comment by shana** [comment] 2017-10-24 19:01
/me shakes fist at Unity

Ok so the problem is that `ImageConversion` got moved out to a separate DLL, which means using `Texture2D` as a DLL location base no longer works. Worse, it got moved to its own assembly - literally a DLL which only contains this class, which means there is no type we can use to get at its location. So, sigh, we'll need to add yet another codepath to this to reference the `UnityEngine.ImageConversionModule.dll` dll to get at this type.

**Comment by joegoldin** [comment] 2017-10-26 19:16
Any idea when this will be fixed in release? Thanks!

**Comment by jennykortina** [comment] 2017-10-30 02:45
+1 on this, would love to get this fixed.  Thank you!

**Comment by StanleyGoldman** [comment] 2017-10-30 13:46
We appreciate the love guys.

![img](https://media.giphy.com/media/3ohjV5Zq8awODwfoLm/giphy.gif)\

We are just busy chasing other stability issues at the moment.
Hopefully in a few weeks we can get to this.

**Comment by jaakaappi** [comment] 2017-10-30 13:53
The plugin is currently completely unusable for new users. Of course I wouldn't know but that sounds quite bad.

**Comment by GalHorowitz** [comment] 2017-10-30 13:54
It's not completely unusable. Only the Beta.

**Comment by StanleyGoldman** [comment] 2017-10-30 14:44
We are still in Alpha ourselves. So we are mostly focusing on core functionality.
Right now it's caching and #23

2017.2 was just made official earlier this month and we haven't gotten the chance to get to it yet.
..but...

1. Some kind folks have described the problem above
2. We take pull requests :)

>"You must construct additional pylons" -Starcraft

![img](https://i.imgur.com/fFPucro.jpg)

**Comment by GalHorowitz** [comment] 2017-10-30 15:27
If anyone needs this right now, I just built and tested what @shiena said, and it works.

**Comment by StanleyGoldman** [comment] 2017-10-30 15:53
### Send that pull request!

![img](https://media.giphy.com/media/xT9IgLrmwMGYFnM10I/giphy.gif)

**Closed** 2017-11-03 23:42 UTC
Labels: bug, unity2017.2
