### ISSUE TITLE
Exceptions thrown when initializing repository in macOS

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#331] opened 2017-09-19 21:03 UTC
## Description
I'm getting exceptions when I try to initialize a new repository in Unity for Mac. This seems to be because I have 2 different versions of git. The strange thing is that both versions of git have lfs installed.

#### Steps to repro
- Create a new project 
- Import the GitHub extension
- Show GitHub window, then click on `Initialize repository`

#### What happens
Instead of the repository being initialized and an initial commit being created, a couple things happen.

**1. I see an exception thrown about `lsf install`**
```
170919-13:25:59 TRACE [ 1] <GitClient>                         LfsInstall
170919-13:25:59 TRACE [ 7] <TaskManager>                       Exception on exclusive thread: 1 git lsf install
```

**2. I also see an exception about `lfs` not being a command**
```
git: 'lfs' is not a git command. See 'git --help'.
  at GitHub.Unity.ProcessTask`1+<RunWithReturn>c__AnonStorey0[System.String].<>m__0 () [0x0010a] in C:\jenkins\workspace\Unity\Unity\src\GitHub.Api\NewTaskSystem\ProcessTask.cs:301 
  at GitHub.Unity.ProcessWrapper.Run () [0x00332] in C:\jenkins\workspace\Unity\Unity\src\GitHub.Api\NewTaskSystem\ProcessTask.cs:170 
  at GitHub.Unity.ProcessTask`1[T].RunWithReturn (Boolean success) [0x0005c] in C:\jenkins\workspace\Unity\Unity\src\GitHub.Api\NewTaskSystem\ProcessTask.cs:311 
  at GitHub.Unity.TaskBase`1[TResult].<TaskBase>m__0 () [0x00000] in C:\jenkins\workspace\Unity\Unity\src\GitHub.Api\NewTaskSystem\TaskBase.cs:406 
```

**3. My repo does not appear to be initialized**
![initialize repo in mac](https://user-images.githubusercontent.com/10103121/30614924-f30bc00a-9d41-11e7-8e45-9ce93130f953.gif)
I press the button and nothing happens. Have to restart Unity to see confirm my repo was initialized. 

After restarting and seeing the repo was initialized, I do not have an initial commit (like I would using Unity for Windows). And looking at the log I see this exception:
```
170919-13:54:50 TRACE [14] <TaskManager>                       Exception on concurrent thread: 2 git log
fatal: your current branch 'master' does not have any commits yet
  at GitHub.Unity.ProcessTaskWithListOutput`1+<RunWithReturn>c__AnonStorey0[GitHub.Unity.GitLogEntry].<>m__0 () [0x000cd] in C:\jenkins\workspace\Unity\Unity\src\GitHub.Api\NewTaskSystem\ProcessTask.cs:423 
  at GitHub.Unity.ProcessWrapper.Run () [0x00332] in C:\jenkins\workspace\Unity\Unity\src\GitHub.Api\NewTaskSystem\ProcessTask.cs:170 
  at GitHub.Unity.ProcessTaskWithListOutput`1[GitHub.Unity.GitLogEntry].RunWithReturn (Boolean success) [0x0005c] in C:\jenkins\workspace\Unity\Unity\src\GitHub.Api\NewTaskSystem\ProcessTask.cs:432 
  at GitHub.Unity.TaskBase`1[TResult].<TaskBase>m__0 () [0x00000] in C:\jenkins\workspace\Unity\Unity\src\GitHub.Api\NewTaskSystem\TaskBase.cs:406 
  at System.Threading.Tasks.Task`1[System.Collections.Generic.List`1[GitHub.Unity.GitLogEntry]].InvokeFuture (System.Object futureAsObj) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <filename unknown>:0 
```

**Comment by StanleyGoldman** [comment] 2017-09-20 16:36
Hey @meaghanlewis we are going to have to share screen to debug this. I'm not able to reproduce it.

**Comment by meaghanlewis** [comment] 2017-09-20 17:48
Some more context for this issue:

I have two different versions of git installed. One at `/usr/local/bin/git` (v2.14.1) and another at `/usr/bin/git`(v2.11.0). Both of these git versions have lfs installed and both use v2.2.1.

For some reason (which is still being determined), using the git at `/usr/local/bin/git` resolves this exception and allows me to initialize a repository with success.

**Comment by meaghanlewis** [comment] 2017-09-21 18:23
Since updating to lfs `v2.3.0` yesterday I no longer have any exceptions @StanleyGoldman. Think can close out this issue now?

**Comment by StanleyGoldman** [comment] 2017-11-06 21:34
Yea, we can close this out.

**Closed by StanleyGoldman** 2017-11-06 21:34 UTC
Labels: bug, macos, more-information-needed
