### ISSUE TITLE
 Git credentials not found.

### ISSUE THREAD

**Issue by tarazhong** [github-for-unity/Unity#329] opened 2017-09-19 15:45 UTC
Hello, when I am pushing I have an issue with my credentials (though I have been correctly authenticated)

Git LFS: (0 of 246 files) 0 B / 15.10 MB
batch response: Git credentials for https://github.com/...git not found.
batch response: Git credentials for https://github.com/...git not found.
batch response: Git credentials for https://github.com/...git not found.
error: failed to push some refs to 'https://github.com/...git'

[github-unity.zip](https://github.com/github-for-unity/Unity/files/1314853/github-unity.zip)

Thank you for your help

**Comment by StanleyGoldman** [comment] 2017-09-19 15:57
Hi @tarazhong, your issue is a duplicate of #278 and will be fixed in the next release. That should be in a few days.

**Closed by StanleyGoldman** 2017-09-19 15:57 UTC
Labels: bug, duplicate
